### PR TITLE
Add TootTally Difficulty Calculator + Misc. Changes

### PR DESCRIPTION
**Pull request by DerpyChap**
This PR adds an "Upload to TootTally", which submits the chart to TootTally's Difficulty Calculator. This provides some useful information to ensure charts are of a high quality, and the implementation here also lets you jump directly to any problematic notes listed.

Outside of that, this PR contains the following changes:
 - `trackRef` is now a field set manually by the user instead of being auotmatically set based on the folder name
   - This along with the TootTally button required some adjusting to the UI to accomodate for it
 - Time Signature and some other numerical values have had their limits increased substantially
 - Allow for fractional BPMs to be entered
   - This required reworking the `num_field` object and introduces a new `is_float` parameter to it
 - Fixes issues with `bgdata` and `improv_zone` fields being lost on file save

I think the README.md and help windows will need updating to reflect these changes, which I might do in a separate PR. I might also need to add some additional checks to prevent submitting to TootTally if some data is invalid (e.g. missing metadata or empty note data).

### CODE REVIEW

**Comment by DerpyChap** [comment]
I've added some simple checks to make sure all chart metadata is filled in before submitting to TootTally.
image

**Comment by DerpyChap** [comment]
I've updated the README.md and the Help window, and I've also rewritten the FFmpeg instructions and added platform specific checks to ensure only the relevant info is displayed.

image

**Comment by towai** [comment]
merging this into a separate branch because i wanna poke at it before merging to master, see if I can't tweak the appearance of the toottally info window a little bit, but cool feature and looks good overall so far!

i'm a bit concerned about just sorting all the Chart's children by position though -- this runs the potential of interspersing stuff like the section handles (or even the lyrics editor and wave preview if someone makes the error of sticking a note at beat 0, given that `sort_custom`'s algorithm is not stable.) with the list of notes. i wonder if it'd be too much of a pain now to shove all the Notes into their own parent like i maybe should've just done in the first place... or, inversely, everything that's not a Note, but then the LyricsEditor still needs to be displayed on top unlike the other ones.

**Comment by DerpyChap** [comment]
I'm no UI or graphics design expert, so I just tried to copy how the results looked on TootTally's own page using the RichTextBox and some BBCode. Any improvements to the design will be very welcome here.

So far I haven't encountered any issues with the sorting (didn't even see any big performance problems which was my biggest concern), but if you have something more optimal in mind for getting a list of notes in the correct order then that'd be great.

**Pull request merged**
